name: "Validate Jira issue in PR"

jobs:
  validate-pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: validate-pr-jira
        if: github.actor != 'steliyan'
        run: "echo xxx"
