name: "Validate Jira issue in PR"

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: validate-pr-jira
        if: github.actor != 'steliyan'
        run: "echo xxx"

  call-pr-labels-workflow:
    if: always()
    needs: validate-pr
    uses: ./.github/workflows/pr-labels.yml
