name: "Validate Jira issue in PR"

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: validate-pr-jira
        run: "echo xxx"
