name: "Validate Jira issue in PR"

on: workflow_call

jobs:
  validate-pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: validate-pr-jira
        run: "echo xxx"
