name: PR

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Tear down the env..."
        run: "echo ci ${{ github.event.pull_request.number }}"
