name: PR

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI
        run: "echo ci ${{ github.event.pull_request.number }}"

      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":"fooo bar zaz"}
          action_url: https://example.com/action
          details_url: https://example.com/details
          actions: |
            [{"label":"Click Me","description":"Click me to get free RAM","identifier":"sent_to_webhook"}]
