name: PR

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Validate PR
        run: echo "Doing some PR validations..."
