name: PR

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI
        run: "echo ci ${{ github.event.pull_request.number }}"

      - name: log
        run: git log -100 --format='%s'
