name: PR

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.actor != 'steliyan'
    # if: github.actor != 'steliyan123'

    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        id: xxx
        run: echo "ci build..."

  call-bar:
    if: always()
    needs: build
    uses: ./.github/workflows/jira.yml
