name: PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'steliyan'

    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        id: xxx
        run: echo "ci build..."

  call-bar:
    if: always()
    needs: build
    uses: ./.github/workflows/jira.yml
