name: PR

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI
        run: "echo ci ${{ github.event.pull_request.number }}"

      - uses: LouisBrunner/checks-action@v1.2.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          action_url: https://example.com/action
          details_url: https://example.com/details
          output: |
            {"summary":"fooo bar zaz [foo](http://example.com)"}
