name: PR

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run CI
        id: xxx
        run: |
          echo "skip0=0" >> $GITHUB_OUTPUT
          echo "skip1=1" >> $GITHUB_OUTPUT

      - name: fail0
        run: false
        if: steps.xxx.outputs.skip0 != 0

      - name: fail1
        run: false
        if: steps.xxx.outputs.skip1 != 0

      - name: log
        run: git log -n 100 --format='%s'
