name: PR

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run CI
        run: "echo ci ${{ github.event.pull_request.number }}"

      # - uses: LouisBrunner/checks-action@v1.2.0
      #   if: success()
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     name: Test XYZ
      #     status: completed
      #     conclusion: success
      #     action_url: https://foo.bar/action
      #     details_url: https://foo.bar/details

      - uses: chrnorm/deployment-action@v1.2.0
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: http://my-app-url.com
          environment: production
          initial_status: success
