name: "Test Nix Flakes"

on:
  push:
    branches:
      - master

jobs:
  nix-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build

      - run: nix flake check
